language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
- pip install --upgrade pip setuptools # Upgrade pip and setuptools to get ones with `wheel` support
- pip install Sphinx sphinx-rtd-theme nose numpydoc
- pip --version

install: 
  - python setup.py install

script:
  - nosetests
  - cd docs && make html

